--- 
development: !map:HashWithIndifferentAccess 
  plugins: inflector, jquery.formbouncer, jquery.hinty
  theme: greycms
  title: GreyCMS
  widgets: ""
  description: Easy, fast, simple content management.
  keywords: cms, content management, professional website
production: 
  plugins: jquery.hinty, jquery.formbouncer, inflector
  theme: greycms
  title: GreyCMS
  widgets: ""
  description: Easy, fast, simple content management.
  keywords: cms, content management, professional website
test: 
  plugins: jquery.hinty, jquery.formbouncer, inflector
  theme: greycms
  title: GreyCMS
  widgets: ""
  description: Easy, fast, simple content management.
  keywords: cms, content management, professional website
