development:
  adapter: mysql
  encoding: utf8
  database: greycms_development
  username: root
  password: 

production:
  adapter: mysql
  encoding: utf8
  database: thelodge
  username: greyrob
  password: -pX8.PK2{4AW

