development:
  adapter: mysql
  encoding: utf8
  database: thelodge
  username: root
  password: 

production:
  adapter: mysql
  encoding: utf8
  database: greyrob_thelodge
  username: greyrob_admin
  password: -pX8.PK2{4AW

